POST http://localhost:5000/videos
Content-Type: application/json

{
    "videos": [
        {
            "isRu": 0,
            "uid": "useridissocool",
            "channelName": "hel",
            "link": "link",
            "reason": "no reason sadly",
            "reasonDetails": null,
            "timeWhenBlocked": 1578175817587185,
            "title": "Мій мікс"
        },
        {
            "isRu": 1,
            "uid": "second vid uid))))))",
            "channelName": "helm",
            "link": "link",
            "reason": "noCyrillic!!!!!",
            "reasonDetails": "ru",
            "timeWhenBlocked": 157817581758185,
            "title": "Мій міксик"
        }
    ]
}

### wrong request
GET http://localhost:5000/addik

### add videos with wrong video data
POST http://localhost:5000/notruvideos
Content-Type: application/json

{
    "videos": [
        {
            "uid": "useridissocool"
        },
        {
            "uid": "second vid uid))))))",
            "channelName": "helm",
            "link": "link",
            "reason": "noCyrillic!!!!!",
            "title": "Мій міксик"
        }
    ]
}

### get videos
GET http://localhost:5000/videos

### test query
GET http://localhost:5000/videos?page=1&limit=5

